import { supabase } from '@/lib/supabase';
import { WebsiteProject } from '@/lib/supabase';

const API_KEY = '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';
const SITE_URL = window.location.origin;
const SITE_NAME = 'Prompt2Site Generator';

export async function generateWebsite(prompt: string): Promise<string> {
  try {
    console.log('Generating website with prompt:', prompt);
    
    const fullPrompt = `Generate a complete, standalone HTML file for a website based on this description: "${prompt}". 
    The HTML should include embedded CSS and JS. Make it responsive, modern, and visually appealing.
    Don't include any placeholders or TODOs. Return ONLY the complete, valid HTML code.`;

    console.log('Sending request to OpenRouter API...');
    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${API_KEY}`,
        "HTTP-Referer": SITE_URL,
        "X-Title": SITE_NAME,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        "model": "deepseek/deepseek-r1:free",
        "messages": [
          {
            "role": "user",
            "content": fullPrompt
          }
        ],
        "max_tokens": 4000 // Adding a max token limit to ensure we get a complete response
      })
    });

    console.log('Response status:', response.status);
    
    if (!response.ok) {
      const errorData = await response.json();
      console.error('API Error response:', errorData);
      throw new Error(errorData.error?.message || `Failed to generate website: HTTP ${response.status}`);
    }

    const data = await response.json();
    console.log('Response received, content length:', data.choices[0].message.content.length);
    
    // Return a fallback HTML if the API fails or returns empty content
    if (!data.choices?.[0]?.message?.content || data.choices[0].message.content.trim().length < 100) {
      console.warn('Empty or very short content received, returning fallback HTML');
      return getFallbackHTML(prompt);
    }
    
    return data.choices[0].message.content.trim();
  } catch (error: any) {
    console.error('Error generating website:', error);
    // Return fallback HTML in case of any error
    return getFallbackHTML(prompt);
  }
}

// Fallback HTML in case the API fails
function getFallbackHTML(prompt: string): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated Website</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      margin: 0;
      padding: 0;
      color: #333;
      background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
      min-height: 100vh;
    }
    .container {
      width: 90%;
      max-width: 1200px;
      margin: 0 auto;
      padding: 2rem;
    }
    header {
      text-align: center;
      padding: 2rem 0;
    }
    h1 {
      font-size: 2.5rem;
      margin-bottom: 1rem;
      color: #2d3748;
    }
    p {
      font-size: 1.1rem;
      margin-bottom: 1.5rem;
    }
    .content {
      background-color: white;
      border-radius: 8px;
      padding: 2rem;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }
    footer {
      text-align: center;
      margin-top: 2rem;
      padding: 1rem 0;
      color: #718096;
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>Your Website</h1>
      <p>Based on: "${prompt}"</p>
    </header>
    <div class="content">
      <p>This is a placeholder website. The AI generation service is temporarily unavailable. Your website would be based on your description: "${prompt}"</p>
      <p>Please try again later or contact support if the issue persists.</p>
    </div>
    <footer>
      <p>Generated by Prompt2Site</p>
    </footer>
  </div>
</body>
</html>
  `;
}

export async function saveProject(
  userId: string, 
  prompt: string, 
  htmlContent: string, 
  title: string
): Promise<string> {
  try {
    const { data, error } = await supabase
      .from('website_projects')
      .insert([
        { user_id: userId, prompt, html_content: htmlContent, title }
      ])
      .select();

    if (error) throw error;
    return data[0].id;
  } catch (error: any) {
    console.error('Error saving project:', error);
    throw new Error(error.message || 'Failed to save project');
  }
}

export async function getUserProjects(userId: string): Promise<WebsiteProject[]> {
  try {
    const { data, error } = await supabase
      .from('website_projects')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return data as WebsiteProject[];
  } catch (error: any) {
    console.error('Error fetching projects:', error);
    throw new Error(error.message || 'Failed to fetch projects');
  }
}

export async function getProjectById(projectId: string): Promise<WebsiteProject> {
  try {
    const { data, error } = await supabase
      .from('website_projects')
      .select('*')
      .eq('id', projectId)
      .single();

    if (error) throw error;
    return data as WebsiteProject;
  } catch (error: any) {
    console.error('Error fetching project:', error);
    throw new Error(error.message || 'Failed to fetch project');
  }
}
