// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouzkozdwyovndestfzrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91emtvemR3eW92bmRlc3RmenJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTE1NTgsImV4cCI6MjA1Nzg4NzU1OH0.taMEFTOR-sxTXMqNQxLJq9FwMHzFx4nxAZEUseX5R_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);